'use client';
import { Breadcrumbs } from "@/components/layout/breadcrumbs";
import { ComplianceHeader } from "@/components/compliance/compliance-header";
import { OverviewStrip } from "@/components/compliance/overview-strip";
import { StandardsAccordion } from "@/components/compliance/standards-accordion";
import { ControlsCards } from "@/components/compliance/controls-cards";
import { DataMap } from "@/components/compliance/data-map";
import { AuditLog } from "@/components/compliance/audit-log";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Info } from "lucide-react";


export default function CompliancePage() {
    return (
        <>
            <Breadcrumbs items={[{ label: 'Dashboard', href: '/dashboard' }, { label: 'Compliance' }]} />
            <main className="py-8">
                <ComplianceHeader />
                
                <Alert className="mt-8 bg-secondary/50">
                    <Info className="h-4 w-4" />
                    <AlertTitle>Informational Use Only</AlertTitle>
                    <AlertDescription>
                        Summaries generated by MedResearchAI are for informational purposes and are not a substitute for professional medical advice, diagnosis, or treatment.
                    </AlertDescription>
                </Alert>

                <div className="mt-8">
                    <OverviewStrip />
                </div>

                <div className="mt-8 grid grid-cols-1 lg:grid-cols-12 lg:gap-8">
                    <div className="lg:col-span-8 space-y-8">
                        <StandardsAccordion />
                        <ControlsCards />
                    </div>
                    <div className="lg:col-span-4 mt-8 lg:mt-0 space-y-8">
                        <DataMap />
                        <AuditLog />
                    </div>
                </div>
            </main>
        </>
    );
}
